controller_list:
  - name: fake_arm_controller
    joints:
      - joint_base_top
      - joint_arm_lower
      - joint_arm_upper
      - joint_lastlink
initial:  # Define initial robot poses.
  - group: arm
    pose: pose1